// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfficeSelfSigningPortal.WebUI.Data;

#nullable disable

namespace OfficeSelfSigningPortal.WebUI.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260928090606_IngestionEntities")]
    partial class IngestionEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OfficeSelfSigningPortal.WebUI.Data.AnalysisJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobId");

                    b.HasIndex("ArtifactId")
                        .IsUnique();

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("OfficeSelfSigningPortal.WebUI.Data.Artifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtifactId");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("OfficeSelfSigningPortal.WebUI.Data.AnalysisJob", b =>
                {
                    b.HasOne("OfficeSelfSigningPortal.WebUI.Data.Artifact", "Artifact")
                        .WithOne("Job")
                        .HasForeignKey("OfficeSelfSigningPortal.WebUI.Data.AnalysisJob", "ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("OfficeSelfSigningPortal.WebUI.Data.Artifact", b =>
                {
                    b.Navigation("Job")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
